/** @type {import('cz-git').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // Add any custom rules here
  },
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
      type: 'Select the type of change that you\'re committing:',
      scope: 'Denote the SCOPE of this change (optional):',
      customScope: 'Denote the SCOPE of this change:',
      subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
      body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
      breaking: 'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
      footerPrefix: 'Select the ISSUES type of changeList by this change (optional):',
      footer: 'List any ISSUES by this change. E.g.: #31, #34:\n',
      confirmCommit: 'Are you sure you want to proceed with the commit above?'
    },
    types: [
      { value: 'feat',     name: 'feat:     ✨  A new feature', emoji: ':sparkles:' },
      { value: 'fix',      name: 'fix:      🐛  A bug fix', emoji: ':bug:' },
      { value: 'docs',     name: 'docs:     📚  Documentation only changes', emoji: ':books:' },
      { value: 'style',    name: 'style:    💎  Changes that do not affect the meaning of the code', emoji: ':gem:' },
      { value: 'refactor', name: 'refactor: 🔨  A code change that neither fixes a bug nor adds a feature', emoji: ':hammer:' },
      { value: 'perf',     name: 'perf:     🚀  A code change that improves performance', emoji: ':rocket:' },
      { value: 'test',     name: 'test:     🚨  Adding missing tests or correcting existing tests', emoji: ':rotating_light:' },
      { value: 'build',    name: 'build:    📦  Changes that affect the build system or external dependencies', emoji: ':package:' },
      { value: 'ci',       name: 'ci:       👷  Changes to our CI configuration files and scripts', emoji: ':construction_worker:' },
      { value: 'chore',    name: 'chore:    🔧  Other changes that don\'t modify src or test files', emoji: ':wrench:' },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: ''
  }
};
