packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": set this to true or false
  esbuild: true
  lightningcss: true
  prisma: true
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - lightningcss
  - prisma
