import { defineConfig } from "vite-plus";

export default defineConfig({
  test: {
    globals: true,
  },
  fmt: {
    ignorePatterns: ["apps/admin/src/routeTree.gen.ts"],
    overrides: [
      {
        files: ["apps/admin/**/*.{js,jsx,mjs,ts,tsx,mts,cts,css}"],
        options: {
          sortTailwindcss: {
            stylesheet: "apps/admin/src/styles.css",
          },
        },
      },
      {
        files: ["apps/website/**/*.{js,jsx,mjs,ts,tsx,mts,cts,css}"],
        options: {
          sortTailwindcss: {
            stylesheet: "apps/website/src/app/globals.css",
          },
        },
      },
      {
        files: ["packages/markdown/**/*.{js,jsx,mjs,ts,tsx,mts,cts,css}"],
        options: {
          sortTailwindcss: {
            stylesheet: "packages/markdown/src/styles.css",
          },
        },
      },
    ],
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
      browser: true,
      node: true,
    },
    ignorePatterns: [
      "node_modules/**",
      "apps/*/node_modules/**",
      "apps/*/dist/**",
      "apps/*/.next/**",
      "apps/*/.tanstack/**",
      "apps/*/.vinxi/**",
      "apps/*/.output/**",
      "apps/*/next-env.d.ts",
      "packages/*/node_modules/**",
      "apps/admin/src/routeTree.gen.ts",
    ],
    rules: {
      "no-array-constructor": "error",
      "no-unused-expressions": "error",
      "no-unused-vars": "error",
      "typescript/ban-ts-comment": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-this-alias": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/triple-slash-reference": "error",
    },
    overrides: [
      {
        files: ["apps/server/**/*.ts"],
        env: {
          node: true,
        },
        plugins: ["node"],
        rules: {
          "typescript/no-explicit-any": "off",
          "typescript/no-floating-promises": "warn",
        },
      },
      {
        files: ["apps/website/**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
        plugins: ["import", "jsx-a11y", "nextjs"],
        env: {
          browser: true,
          node: true,
        },
        globals: {
          AudioWorkletGlobalScope: "readonly",
          AudioWorkletProcessor: "readonly",
          currentFrame: "readonly",
          currentTime: "readonly",
          registerProcessor: "readonly",
          sampleRate: "readonly",
          WorkletGlobalScope: "readonly",
        },
        rules: {
          "better-tailwindcss/enforce-canonical-classes": [
            "error",
            {
              entryPoint: "src/app/globals.css",
              cwd: "apps/website",
              rootFontSize: 16,
            },
          ],
          "react/display-name": "error",
          "react/jsx-key": "error",
          "react/jsx-no-comment-textnodes": "error",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-target-blank": "off",
          "react/jsx-no-undef": "error",
          "react/no-children-prop": "error",
          "react/no-danger-with-children": "error",
          "react/no-direct-mutation-state": "error",
          "react/no-find-dom-node": "error",
          "react/no-is-mounted": "error",
          "react/no-render-return-value": "error",
          "react/no-string-refs": "error",
          "react/no-unescaped-entities": "error",
          "react/no-unknown-property": "off",
          "react/no-unsafe": "off",
          "react/react-in-jsx-scope": "off",
          "react/require-render-return": "error",
          "import/no-anonymous-default-export": "warn",
          "jsx-a11y/alt-text": [
            "warn",
            {
              elements: ["img"],
              img: ["Image"],
            },
          ],
          "jsx-a11y/aria-props": "warn",
          "jsx-a11y/aria-proptypes": "warn",
          "jsx-a11y/aria-unsupported-elements": "warn",
          "jsx-a11y/role-has-required-aria-props": "warn",
          "jsx-a11y/role-supports-aria-props": "warn",
          "nextjs/google-font-display": "warn",
          "nextjs/google-font-preconnect": "warn",
          "nextjs/next-script-for-ga": "warn",
          "nextjs/no-async-client-component": "warn",
          "nextjs/no-before-interactive-script-outside-document": "warn",
          "nextjs/no-css-tags": "warn",
          "nextjs/no-head-element": "warn",
          "nextjs/no-html-link-for-pages": "warn",
          "nextjs/no-img-element": "warn",
          "nextjs/no-page-custom-font": "warn",
          "nextjs/no-styled-jsx-in-document": "warn",
          "nextjs/no-sync-scripts": "warn",
          "nextjs/no-title-in-document-head": "warn",
          "nextjs/no-typos": "warn",
          "nextjs/no-unwanted-polyfillio": "warn",
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "warn",
        },
      },
      {
        files: ["packages/markdown/**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
        env: {
          browser: true,
          node: true,
        },
        rules: {
          "better-tailwindcss/enforce-canonical-classes": [
            "error",
            {
              entryPoint: "src/styles.css",
              cwd: "packages/markdown",
              rootFontSize: 16,
            },
          ],
          "react/display-name": "error",
          "react/jsx-key": "error",
          "react/jsx-no-comment-textnodes": "error",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-target-blank": "off",
          "react/jsx-no-undef": "error",
          "react/no-children-prop": "error",
          "react/no-danger-with-children": "error",
          "react/no-direct-mutation-state": "error",
          "react/no-find-dom-node": "error",
          "react/no-is-mounted": "error",
          "react/no-render-return-value": "error",
          "react/no-string-refs": "error",
          "react/no-unescaped-entities": "error",
          "react/no-unknown-property": "off",
          "react/no-unsafe": "off",
          "react/react-in-jsx-scope": "off",
          "react/require-render-return": "error",
          "react/rules-of-hooks": "error",
          "react/exhaustive-deps": "warn",
        },
      },
      {
        files: ["apps/admin/**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
        rules: {
          "better-tailwindcss/enforce-canonical-classes": [
            "error",
            {
              entryPoint: "src/styles.css",
              cwd: "apps/admin",
              rootFontSize: 16,
            },
          ],
        },
      },
      {
        files: ["**/*.{ts,tsx,mts,cts}"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-class-members": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-var": "error",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
      {
        name: "better-tailwindcss",
        specifier: "eslint-plugin-better-tailwindcss",
      },
    ],
  },
});
