import type {
  AdminAgentTaskCatalogItem,
  AdminAgentTaskControlCatalogItem,
  AdminAgentTaskName,
} from "./admin/agent.js";

export type { AdminMeResponse, AdminUserResponse } from "./admin/auth.js";
export type {
  AdminAgentActionExecutionResultItemResponse,
  AdminAgentActionExecutionResultResponse,
  AdminAgentAssistantMessage,
  AdminAgentAutomationPolicyMode,
  AdminAgentAutomationPolicyResponse,
  AdminAgentCapabilityId,
  AdminAgentCapabilityResponse,
  AdminAgentCapabilityStatus,
  AdminAgentChatMessage,
  AdminAgentChatMessageRole,
  AdminAgentConversationMessageResponse,
  AdminAgentConversationMessagesResponse,
  AdminAgentContextEntry,
  AdminAgentFindingCategory,
  AdminAgentFindingDecision,
  AdminAgentFindingDecisionResultResponse,
  AdminAgentFindingResponse,
  AdminAgentFindingSeverity,
  AdminAgentFindingStatus,
  AdminAgentFindingTargetArticleResponse,
  AdminAgentFindingTargetAuthorResponse,
  AdminAgentFindingTargetResponse,
  AdminAgentFindingTargetType,
  AdminAgentHomeResponse,
  AdminAgentInteractionEvent,
  AdminAgentProposedAction,
  AdminAgentRecentActionResponse,
  AdminAgentTaskSummaryResponse,
  AdminAgentTaskStatus,
  AdminAgentTaskApprovalInterruptionResponse,
  AdminAgentTaskAvailability,
  AdminAgentTaskControlAction,
  AdminAgentTaskControlCatalogItem,
  AdminAgentTaskCatalogItem,
  AdminAgentTaskListQuery,
  AdminAgentTaskListResponse,
  AdminAgentTaskName,
  AdminAgentTaskOutputResponse,
  AdminAgentTaskTimelineEventResponse,
  AdminAgentTaskTimelineEventStatus,
  ControlAdminAgentTaskRequest,
  ControlAdminAgentTaskResponse,
  DecideAdminAgentFindingsRequest,
  DecideAdminAgentFindingsResponse,
  ResumeAdminAgentTaskRequest,
  ResumeAdminAgentTaskResponse,
  StartAdminAgentTaskRequest,
  StartAdminAgentTaskResponse,
} from "./admin/agent.js";
export type {
  AdminOperationLogAction,
  AdminOperationLogListQuery,
  AdminOperationLogListResponse,
  AdminOperationLogResponse,
} from "./admin/audit.js";
export type {
  AdminArticleAiSummaryStatus,
  AdminArticleCategoryListQuery,
  AdminArticleCategoryListResponse,
  AdminArticleCategoryResponse,
  AdminArticleDetailResponse,
  AdminArticleEditorDraftResponse,
  AdminArticleEditorDraftValues,
  AdminArticleListItemResponse,
  AdminArticleListQuery,
  AdminArticleListResponse,
  AdminArticleStatus,
  AdminArticleTaxonomyOption,
  AdminArticleTaxonomyOptionsResponse,
  AdminArticleTagListQuery,
  AdminArticleTagListResponse,
  AdminArticleTagResponse,
  CreateAdminArticleRequest,
  CreateAdminArticleCategoryRequest,
  CreateAdminArticleTagRequest,
  MergeAdminArticleTagRequest,
  SaveAdminArticleEditorDraftRequest,
  UpdateAdminArticleRequest,
  UpdateAdminArticleCategoryRequest,
  UpdateAdminArticleTagRequest,
} from "./admin/articles.js";
export type {
  AdminArticleCommentArticleResponse,
  AdminArticleCommentAuthorResponse,
  AdminArticleCommentListItemResponse,
  AdminArticleCommentListQuery,
  AdminArticleCommentListResponse,
  AdminArticleCommentParentResponse,
  AdminArticleCommentStatus,
  UpdateAdminArticleCommentRequest,
} from "./admin/comments.js";
export type {
  AdminGuestbookMessageAuthorResponse,
  AdminGuestbookMessageListItemResponse,
  AdminGuestbookMessagesQuery,
  AdminGuestbookMessagesResponse,
  AdminGuestbookMessageStatus,
  UpdateAdminGuestbookMessageRequest,
} from "./admin/guestbook.js";
export type {
  AdminSiteAnnouncementResponse,
  AdminSiteConfigResponse,
  UpdateAdminSiteAnnouncementRequest,
  UpdateAdminSiteSettingsRequest,
} from "./admin/site-config.js";
export type {
  ArticleCategoryDetailResponse,
  ArticleCategoryListResponse,
  ArticleCategorySummary,
  ArticleAiSummaryResponse,
  ArticleDetailResponse,
  ArticleListItemResponse,
  ArticleListQuery,
  ArticleListResponse,
  ArticleOrigin,
  ArticleSource,
  ArticleTagSummary,
  ArticleTagDetailResponse,
  ArticleTagListQuery,
  ArticleTagListResponse,
} from "./public/articles.js";
export type { AuthUserResponse } from "./public/auth.js";
export type {
  ArticleCommentAuthor,
  ArticleCommentLikeResponse,
  ArticleCommentResponse,
  ArticleCommentsQuery,
  ArticleCommentsResponse,
  CreateArticleCommentRequest,
} from "./public/comments.js";
export type {
  CreateGuestbookMessageRequest,
  GuestbookMessageAuthor,
  GuestbookMessageLikeResponse,
  GuestbookMessageResponse,
  GuestbookMessagesQuery,
  GuestbookMessagesResponse,
} from "./public/guestbook.js";
export type { PaginatedResponse, PaginationMeta } from "./public/pagination.js";
export type {
  SiteAnnouncementResponse,
  SiteConfigResponse,
  SiteHomeConfigResponse,
  SiteNavigationItemResponse,
  SiteSocialLinkResponse,
} from "./public/site-config.js";

const adminAgentTaskControls = [
  {
    action: "cancel",
    allowedStatuses: ["PENDING", "RUNNING", "WAITING_FOR_APPROVAL"],
    availability: "AVAILABLE",
    description: "管理员希望停止尚未完成的业务处理时使用。",
    requiresPausedTask: false,
    title: "取消",
  },
  {
    action: "branch",
    allowedStatuses: ["WAITING_FOR_APPROVAL"],
    availability: "AVAILABLE",
    description: "管理员希望基于同一个暂停点换一种处理方向时使用。",
    requiresPausedTask: true,
    title: "另开处理",
  },
  {
    action: "retry",
    allowedStatuses: ["COMPLETED", "FAILED", "CANCELLED"],
    availability: "AVAILABLE",
    description: "管理员希望对已结束或失败的业务处理重新执行时使用。",
    requiresPausedTask: false,
    title: "重新尝试",
  },
] as const satisfies readonly AdminAgentTaskControlCatalogItem[];

const adminAgentMultiTaskControls = [
  ...adminAgentTaskControls,
  {
    action: "refresh",
    allowedStatuses: ["COMPLETED", "FAILED"],
    availability: "AVAILABLE",
    description: "管理员希望同步已完成子任务结果并刷新跨域协作摘要时使用。",
    requiresPausedTask: false,
    title: "刷新汇总",
  },
] as const satisfies readonly AdminAgentTaskControlCatalogItem[];

const adminAgentTaskCatalog = [
  {
    availability: "AVAILABLE",
    capabilityId: "comments",
    controls: adminAgentTaskControls,
    description: "读取评论上下文，生成风险建议，并在写操作前请求管理员确认。",
    requiresApprovalForWrites: true,
    supportsHumanApproval: true,
    supportsStart: true,
    title: "评论治理分析",
    taskName: "comment_moderation_analysis",
  },
  {
    availability: "AVAILABLE",
    capabilityId: "articles",
    controls: adminAgentTaskControls,
    description: "协助选题、草稿检查、发布前巡检和摘要生成。",
    requiresApprovalForWrites: false,
    supportsHumanApproval: true,
    supportsStart: true,
    title: "文章协作",
    taskName: "article_assistance",
  },
  {
    availability: "AVAILABLE",
    capabilityId: "site",
    controls: adminAgentTaskControls,
    description: "巡检首页、导航、公告和社交链接，生成站点管理规划。",
    requiresApprovalForWrites: true,
    supportsHumanApproval: true,
    supportsStart: true,
    title: "站点巡检",
    taskName: "site_config_review",
  },
  {
    availability: "AVAILABLE",
    capabilityId: "audit",
    controls: adminAgentTaskControls,
    description: "解释最近管理动作、追踪治理记录，并辅助定位风险操作。",
    requiresApprovalForWrites: false,
    supportsHumanApproval: true,
    supportsStart: true,
    title: "审计分析",
    taskName: "audit_review",
  },
  {
    availability: "AVAILABLE",
    capabilityId: null,
    controls: adminAgentMultiTaskControls,
    description: "跨文章、评论、站点和审计的协作入口，只在对话中协调多个业务流程。",
    requiresApprovalForWrites: true,
    supportsHumanApproval: true,
    supportsStart: true,
    title: "跨域协作",
    taskName: "multi_task_orchestration",
  },
] as const satisfies readonly AdminAgentTaskCatalogItem[];

const startableAdminAgentTaskNames = [
  "comment_moderation_analysis",
  "article_assistance",
  "site_config_review",
  "audit_review",
  "multi_task_orchestration",
] as const satisfies readonly AdminAgentTaskName[];

export { adminAgentTaskCatalog, adminAgentTaskControls, startableAdminAgentTaskNames };
